- dockstore-client/src/main/java/io/dockstore/client/cli/JCommanderUtility.java
- dockstore-client/src/main/java/io/dockstore/client/cli/nested/AbstractEntryClient.java
- dockstore-client/src/main/java/io/dockstore/client/cli/nested/WorkflowClient.java
This PR is meant normalize the client facing mentions of Dockstore from 'the dockstore' in some places to 'Dockstore'.
> Change mentions of 'the dockstore' to 'Dockstore'

- .travis.yml
- dockstore-cli-integration-testing/src/test/java/io/dockstore/common/CommonTestUtilities.java
- scripts/decrypt.sh
Regression tests are failing in `release/1.8`, looks like they now need confidential data for some reason
Also have .travis.yml pass validation
> Regression tests should test with 1.7.4

- dockstore-client/src/main/java/io/dockstore/client/cli/JCommanderUtility.java
For dockstore/dockstore#1971
Clarify that one of the flags are required.  Also mention that only CWL supports YAML
> Make test parameter flags required

- dockstore-client/src/main/java/io/dockstore/client/cli/ArgumentUtility.java
- dockstore-client/src/main/java/io/dockstore/client/cli/nested/WorkflowClient.java
Main issue: https://github.com/dockstore/dockstore/issues/3605
Original bug report noted confusing duplicate workflow names appearing in search results:
```
$ dockstore workflow search --pattern md5sum
MATCHING WORKFLOWS
---------------------------------------------
NAME                                                             DESCRIPTION                                          GIT REPO                                                                 PUBLISHED
github.com/coverbeck/md5sum-dockstore-yml                                                                             git@github.com:coverbeck/md5sum-dockstore-yml.git                        Yes
github.com/DataBiosphere/toolbox                                 This wraps the md5sum tool with a checker workf... …
```
> use full workflow path when printing workflow list

- dockstore-cli-integration-testing/src/test/java/io/dockstore/client/cli/CromwellIT.java
Part 1 of 2 for preliminary investigation to https://ucsc-cgl.atlassian.net/browse/SEAB-2622
Part 2: https://github.com/dockstore/dockstore/pull/4130
First step is to move client tests back to client (assuming dockstore/dockstore's test is "correct"). This allows for easier debugging (more info than "System Exit(3)")
> Copy from CromwellIT tests from dockstore/dockstore

- .circleci/config.yml
- .github/workflows/mvnw.yml
- .mvn/wrapper/maven-wrapper.properties
- dockstore-cli-integration-testing/src/test/java/io/dockstore/client/cli/GeneralWorkflowIT.java
- pom.xml
- scripts/install-tests.sh
Working on https://github.com/dockstore/dockstore/issues/4448 and  https://github.com/dockstore/dockstore/issues/4449
Main repo is already up-to-date actually, updating wrapper 
Using query to get latest timestamped version and then trim away the timestamp (which seems weird, there is probably a better way to do this)
Standardizing with Maven 3.8.1 and Java 11.0.11
To see how this works with the nightly build see https://github.com/dockstore/dockstore-cli/pull/83/commits/acdbff97127124fb2eccc48337a7991cf2dd45b9 ("Looks like openjdk image has old maven" has the working github action cron build) Following commits should only affect circle ci and not github actions (which is used for the cron test of the cli)
For future updates, the Go failure on the update looks like it is due to …
> Update mvnw and try snapshot query

- dockstore-client/src/main/java/io/dockstore/client/cli/nested/AbstractEntryClient.java
- dockstore-client/src/test/java/io/dockstore/client/cli/AbstractEntryClientTestIT.java
Adds support for the `/service-info` WES endpoint (https://ga4gh.github.io/workflow-execution-service-schemas/docs/#operation/GetServiceInfo). This will make testing initial AGC work easier. 
Command: `dockstore workflow wes service-info`
The Dockstore-cli help command looks like:
And the response printed looks like: 
or
(Note: the null responses are dependent on what the WES endpoint provides, and the generated ServiceInfo class explicitly prints `class ServiceInfo` as part of the info dump, which seems odd.)
> Service-info endpoint support for WES

- .github/workflows/cron.yml
- .github/workflows/mvnw.yml
- .mvn/jvm.config
- pom.xml
CLI version of getting unit tests working in Java 17
Not enforcing Java 17 yet since it runs on the users end
But this stops us from checking in anything that doesn't compile and unit test properly in Java 17 at least
Issue
https://ucsc-cgl.atlassian.net/browse/DOCK-1436
Follows https://github.com/dockstore/dockstore/pull/4492
> Enforce that we do not introduce any code incompatible with Java 17 LTS

- .github/workflows/cron.yml
Cron on 2021-11-16 failed to trigger message on Slack
Looks like mismatch between secret and cron.yml
Problematic action is https://github.com/slackapi/slack-github-action#slack-incoming-webhook-route
> cron.yml fix notify

- .circleci/config.yml
- dockstore-cli-integration-testing/generated/src/main/resources/pom.xml
- dockstore-client/generated/src/main/resources/pom.xml
- dockstore-file-plugin-parent/generated/src/main/resources/pom.xml
- openapi-java-wes-client/generated/src/main/resources/pom.xml
- reports/generated/src/main/resources/pom.xml
- support/generated/src/main/resources/pom.xml
Skip the Pom file check if a tag is pushed, because when doing a release maven perform does not do a build which can cause the generated pom files to be different from those that are in the repository.
> skip pom check for tags

- dockstore-client/src/main/java/io/dockstore/client/cli/nested/WesLauncher.java
- dockstore-client/src/test/java/io/dockstore/client/cli/WesLauncherIT.java
Followup to: https://github.com/dockstore/dockstore-cli/pull/107
This parameter is now required to be non-null. There are two separate 'bioworkflow' strings to choose from:
1. `WorkflowSubClass.BIOWORKFLOW.toString()` -> `"BIOWORKFLOW"`
2. `WorkflowClient.BIOWORKFLOW` -> `"bioworkflow"`
I see `WorkflowSubClass.BIOWORKFLOW.toString()` being used to make the same function call [elsewhere](https://github.com/dockstore/dockstore-cli/pull/107/files#diff-e679fea995a50bafa2ef51b5d382128204370e4a29ef6509d0e2271a89dc3981), so I'm opting for it here, but both are used throughout the CLI. Either seems to work. Is there an important difference between the two? I believe both are processed as case-insensitive.
This parameter
> API parameter is required to be non-null.

- dockstore-client/src/main/java/io/dockstore/client/cli/nested/ApiClientExtended.java
Ticket: https://ucsc-cgl.atlassian.net/browse/SEAB-3487
This PR introduces some additional exception handling for the WES functionality. Based on the WES API calls, the list of status codes (https://ga4gh.github.io/workflow-execution-service-schemas/docs/#tag/WorkflowExecutionService) we can expect to receive from a WES server includes: 
1. OK: `200`
2. Malformed: `400`
3. Request is unauthorized: `401`
4. Requester is unauthorized: `403`
5. Target not found: `404`
6. Internal server error: `500`
I found that between DNAStack and AGC WES servers, some of the error messages were either in odd formats or not verbose (For example, in the case of a `403`, DNAStack returns the message `error`, and AGC returns the JSON string `{"message":"The security token included in the request is …
> Improved WES exception handling

- dockstore-client/bin/dockstore
- dockstore-client/src/main/java/io/dockstore/client/cli/Client.java
Addresses https://ucsc-cgl.atlassian.net/browse/SEAB-3147
Upgrading CLI from 1.10.0 to 1.11.0 works but throws error message
Return the stdout and stderr so you can see message from dockstore script
Don't report a failure just because the JAR is already there.
> Don't throw error message if Jar already present

- dockstore-client/src/main/java/io/github/collaboratory/cwl/CWLClient.java
This PR adds a missing null check to the code that determines which input files a workflow needs to run.  Without the null check, if the code encountered an input field with a map value, and said map did not include either a `path` or `location` key, the cli would attempt to manipulate a null path and die.  
I also did a small amount of refactoring.  I wasn't sure if we try to sync the CLI release with the webservice/UI, so I didn't want to change much...
Now, the workflow described in the issue fails with a different, legitimate error, due to a missing input:
`19:34:34.223 [pool-2-thread-1] ERROR io.dockstore.common.FileProvisioning - Could not copy /mnt/data/ucsd-dartfish/ex1/0_Raw_chcorr/ to /Users/svonworl/tmp/spatial-transcriptomics-pipeline/datastore/launcher-5e3038e8 …
> Feature/dock 1851/cli attempts erroneous file download

- dockstore-cli-integration-testing/src/test/java/io/dockstore/client/cli/WesToilIT.java
- dockstore-client/generated/src/main/resources/pom.xml
- dockstore-client/pom.xml
- dockstore-client/src/main/java/io/dockstore/client/cli/nested/AbstractEntryClient.java
This PR changes the print formatting of WES responses. We are now printing the responses as pure JSON (rather than Stringified Objects). So the user will see:
```
{
"workflow_type_versions" : {
"WDL" : {
"workflow_type_version" : [ "1.0", "draft-2" ]
}
},
"supported_wes_versions" : [ "1.0.0" ],
"supported_filesystem_protocols" : null,
"workflow_engine_versions" : null,
"default_workflow_engine_parameters" : null,
"system_state_counts" : null,
"auth_instructions_url" : null,
"contact_info_url" : null,
"tags" : {
"cromwell_service_health" : "True",
"description" : "WES adapter for Cromwell workflow engine service.",
"name" : "remote_cromwell_wes_adapter",
"updated_at" : "2022-02-23T17:37:54.672500Z"
}
}
```
instead of:
```
class ServiceInfo {
workflowTypeVersions: {WDL=class …
```
> WES response JSON printing

- encrypt.sh
- scripts/decrypt.sh
Add a flag to force the encrypt/decrypt scripts to use the SHA-256 message digest.  Without said flag, some [older?] openssl implementations default to a different digest.
> make encrypt/scripts use sha256 digest

- dockstore-cli-integration-testing/src/test/java/io/dockstore/client/cli/BasicIT.java
- dockstore-cli-integration-testing/src/test/java/io/dockstore/client/cli/ClientIT.java
- dockstore-cli-integration-testing/src/test/java/io/dockstore/client/cli/CromwellIT.java
- dockstore-cli-integration-testing/src/test/java/io/dockstore/client/cli/GeneralIT.java
- dockstore-cli-integration-testing/src/test/java/io/dockstore/client/cli/GeneralWorkflowIT.java
- dockstore-cli-integration-testing/src/test/java/io/dockstore/client/cli/GitHubAppToolIT.java
- dockstore-cli-integration-testing/src/test/java/io/dockstore/client/cli/MockedIT.java
- dockstore-cli-integration-testing/src/test/java/io/dockstore/client/cli/NotificationsIT.java
- dockstore-cli-integration-testing/src/test/java/io/dockstore/client/cli/SingularityIT.java
- dockstore-cli-integration-testing/src/test/java/io/dockstore/client/cli/StarIT.java
- dockstore-cli-integration-testing/src/test/java/io/dockstore/client/cli/WDLWorkflowIT.java
- dockstore-cli-integration-testing/src/test/java/io/dockstore/client/cli/WesToilIT.java
- dockstore-cli-integration-testing/src/test/java/io/dockstore/client/cli/WorkflowIT.java
- dockstore-cli-integration-testing/src/test/java/io/dockstore/common/FlushingSystemErrRule.java
- dockstore-cli-integration-testing/src/test/java/io/dockstore/common/FlushingSystemOutRule.java
- dockstore-client/src/test/java/io/dockstore/client/cli/AbstractEntryClientTestIT.java
- dockstore-client/src/test/java/io/dockstore/client/cli/ClientTestIT.java
- dockstore-client/src/test/java/io/dockstore/client/cli/LaunchNoInternetTestIT.java
- dockstore-client/src/test/java/io/dockstore/client/cli/LaunchTestIT.java
- dockstore-client/src/test/java/io/dockstore/client/cli/NextflowIT.java
- dockstore-client/src/test/java/io/dockstore/client/cli/WesFileTest.java
- dockstore-client/src/test/java/io/dockstore/client/cli/WesLauncherTest.java
- dockstore-client/src/test/java/io/dockstore/client/cli/WorkflowInDirectoryTestIT.java
- dockstore-client/src/test/java/io/dockstore/common/FlushingSystemErrRule.java
- dockstore-client/src/test/java/io/dockstore/common/FlushingSystemOutRule.java
- dockstore-client/src/test/java/io/dockstore/common/WesRequestDataTest.java
- dockstore-client/src/test/java/io/github/collaboratory/TabExpansionTest.java
- dockstore-client/src/test/java/io/github/collaboratory/cwl/LauncherIT.java
A CLI integration test had become very flaky and was essentially blocking development.  The problem was that all output sometimes did not completely propagate to the associated JUnit `SystemOutRule` and `SystemErrRule` objects, which the tests use to log `stdout`/`stderr`, so the test would sometimes retrieve an incomplete output and fail.  The theory is the logging system wasn't flushing, or the output was stuck in a queue/buffer and not processed by a logging thread in time, or something like that.
This PR adds a pause-and-flush before retrieving the logged stderr/stdout, via new extending classes `FlushingSystemOutRule` and `FlushingSystemErrRule`, which are instantiated as a replacement.
This PR fixes all tests in `dockstore-cli`.  Within `dockstore-cli`, there did not appear to be a …
> flush test output

- dockstore-client/src/main/java/io/dockstore/client/cli/ArgumentUtility.java
- dockstore-client/src/main/java/io/dockstore/client/cli/nested/WorkflowClient.java
This PR changes the dockstore CLI to print information about the exception thrown upon a launch failure (the type of exception, message [if present], and a stacktrace), in addition to the error message.  It also includes a cleanup of the adjacent launch code. 
**Issue**
https://ucsc-cgl.atlassian.net/browse/DOCK-2057
dockstore/dockstore#4713
> Feature/dock 2057/improve launch failure message

- dockstore-client/src/main/java/io/dockstore/client/cli/nested/AbstractEntryClient.java
WES support in the CLI is tested with WDL, so changed the note to that effect. I also changed the all-caps text because it seemed excessively 'loud', but can change it back if that's the recommended format for notes.
This is also seems like a good PR to finish off the develop changes and cut the release branch.
> Move WES out of beta

- pom.xml
Forget if snyk respects test scope dependencies, checking 
Looks like they have the intention to ignore test scope dependencies https://github.com/snyk/cli/issues/1574
This is for https://ucsc-cgl.atlassian.net/browse/SEAB-4179
> see if this makes snyk happier

- dockstore-cli-integration-testing/src/test/java/io/dockstore/client/cli/ClientIT.java
- dockstore-client/src/main/java/io/dockstore/client/cli/JCommanderUtility.java
- dockstore-client/src/main/java/io/dockstore/client/cli/nested/AbstractEntryClient.java
- dockstore-client/src/main/java/io/dockstore/client/cli/nested/WorkflowClient.java
This PR removes residual mentions of the command line argument `--tsv`.
> Remove residual mentions of `--tsv`

- .circleci/config.yml
An update in liquibase has caused every changeset to be logged to stdout. Including messages such as,
```
Running Changeset: migrations.1.12.0.xml::topicPhaseTwoChanges::gluu (generated)
Running Changeset: migrations.1.12.0.xml::clearCwlToolTableJson::svonworl
Running Changeset: migrations.1.12.0.xml::checksumsForNullContent::coverbeck
Running Changeset: migrations.1.12.0.xml::addAppToolEvents::dyuen (generated)
Running Changeset: migrations.1.12.0.xml::orcidAuthorInfo::ktran (generated)
Running Changeset: migrations.1.13.0.xml::migrateBioToBlogLink::ktran
Running Changeset: migrations.1.13.0.xml::convertUserProfileEmptyStringToNull::ktran
Running Changeset: migrations.1.13.0.xml::add_constraints_to_user_profile::ajandu
```
which is making it difficult to determine the …
> Removed Liquibase Changeset Message from Output in CircleCI

- dockstore-client/src/main/java/io/dockstore/client/cli/YamlVerifyUtility.java
Very simple change. Realized the error message in the Yaml Validate feature for when the yaml is invalid was missing a space. This PR corrects that error. 
**Before**
```
Your .dockstore.yml is invalid:
correct-directory/.dockstore.yml is not a valid yamlfile:
```
**After**
```
Your .dockstore.yml is invalid:
correct-directory/.dockstore.yml is not a valid yaml file:
```
> Corrected missing space in error message

- .github/workflows/mvnw.yml
Reduce pinning for github provided github actions
Just see if github actions are continuing to pass
**Issue**
https://ucsc-cgl.atlassian.net/browse/SEAB-5000
> reduce pin

- .github/dependabot.yml
automatically assign reviewers to dependabot tickets for better visibility
n/a
**Issue**
https://ucsc-cgl.atlassian.net/browse/SEAB-5002
https://github.blog/changelog/2020-07-15-assign-a-github-team-to-review-dependabot-pull-requests/
> assign reviewers for dependabot

- dockstore-client/src/test/java/io/dockstore/client/cli/LaunchTestIT.java
- dockstore-client/src/test/resources/1st-workflow-12.cwl
- dockstore-client/src/test/resources/class-operation.cwl
This PR adds a couple of tests that help to confirm CLI compatibility with CWL version 1.2.
Per the spec, CWL changed as follows between version 1.1 and 1.2:
https://www.commonwl.org/v1.2/Workflow.html#Changelog
Not much is different.
Knowing how we parse and a bit about how the CLI is structured, my theory was that if our CLI supports CWL v1.1, and the CLI could process a v1.2 workflow that contained either a "when" clause or an "Operation", that it probably can successfully process a very large proportion of v1.2 workflows.  So, I added a test corresponding to each of those two cases.
As it turns out, the CLI processes a workflow with a step containing an "Operation" with no problems, but when cwltool is invoked to run it, it fails because an "Operation" is defined as a …
> SEAB-5021:  Confirm support for CWL Version 1.2

- dockstore-cli-integration-testing/src/test/java/io/dockstore/common/ToilCompatibleTest.java
- dockstore-client/src/main/java/io/dockstore/client/cli/Client.java
The CLI requires the use of the `ToilCompatibleTest` class. However, `ToilCompatibleTest` class was recently removed from `dockstore/dockstore` in this [PR](https://github.com/dockstore/dockstore/pull/5297). Meaning that the CLI cannot run off the current `dockstore/dockstore` repo. This PR adds the `ToilCompatibleTest` to the CLI.
To review this ticket, you should
**Security**
\
> Added a  ToilCompatibleTest class to CLI

- dockstore-client/src/main/java/io/dockstore/client/cli/Client.java
This PR removes the `upgrade-unstable` message in both `dockstore --upgrade` and `dockstore --version`
Review that the message is removed accordingly.
**Issue**
https://github.com/dockstore/dockstore/issues/5054
**Security**
> DOCK-2219: removed upgrade to unstable version message

- THIRD-PARTY-LICENSES.txt
- dockstore-client/generated/src/main/resources/pom.xml
- dockstore-client/pom.xml
- dockstore-client/src/main/java/io/dockstore/client/cli/nested/CromwellLauncher.java
- dockstore-client/src/main/java/io/dockstore/common/FileProvisionUtil.java
- pom.xml
Add a progress bar to cromwell provisioning by using vfs2
https://github.com/dockstore/dockstore/issues/1520
1. Remove `~/.dockstore/self-installs/` and `~/.dockstore/libraries/`
2. Run just `dockstore` and see progress bar for our jar
3. Run `dockstore workflow launch --entry github.com/dockstore-testing/Metaphlan-WDL:master --json Dockstore.json` with any `json` stub and see progress bar for cromwell
**Issue**
https://github.com/dockstore/dockstore/issues/1520
**Security**
None
> update vfs, hook-up cromwell for progress bar

- dockstore-client/src/main/java/io/dockstore/client/cli/Client.java
Ever changed your `config` file and forgot which server you were accessing? Well we have a solution for you ;)  This pr adds the `server-url` from your config file to the existing `--server-metadata` command.
Example output:
```
$ dockstore --server-metadata
{
"apiVersion": "2.0.0",
"country": "CAN",
"friendlyName": "Dockstore",
"version": "1.13.1"
}
server-url: https://dockstore.org/api
```
Charles brought up a great observation that this command is using the TRS 2.0.0-beta.2 API similar to a [previous ticket](https://ucsc-cgl.atlassian.net/browse/DOCK-2300) so I've also created a [new ticket](https://ucsc-cgl.atlassian.net/browse/SEAB-5206) to switch to the TRS 2.0.0 API.
Build changes and run the `--server-metadata` command, ensure the …
> Display server-url

- dockstore-client/src/main/java/io/github/collaboratory/wdl/WDLClient.java
- dockstore-client/src/test/java/io/dockstore/client/cli/LaunchTestIT.java
- dockstore-client/src/test/resources/commandOnly.wdl
- dockstore-client/src/test/resources/sub-workflow-task.wdl
- dockstore-client/src/test/resources/sub-workflow-test.json
- dockstore-client/src/test/resources/sub-workflow-test.wdl
- dockstore-client/src/test/resources/wfAndCallOnly.wdl
Currently, the `CLI` does not accept WDL workflows that do not contain `task`, `command`, or `output` in the `--entry` file. However, it is possible to have a valid WDL workflow that does not contain these fields, through the use of [sub-workflows](https://cromwell.readthedocs.io/en/stable/SubWorkflows/), an example given [here](https://github.com/openwdl/learn-wdl/tree/master/1_script_examples/1_hello_worlds/7_subworkflow).
To fix this, I have modified the method `WDLClient.check(file)` such that it only sends an error message if either `workflow` or `call` are not found in the `--entry` file and it gives a warning to the user if the `--entry` is missing `task`, `command`, or `output`.
I am giving the warning as if the WDL is invalid, when it is launched, it will give the …
> Fix Incorrect WDL validation

- dockstore-client/src/main/java/io/dockstore/client/cli/Client.java
Spin off ticket from DOCK-2300 (UI Relying on Beta TRS) this ticket switches from using `TRS 2.0.0-beta.2` API to `TRS 2.0.0` in the CLI. Appears to only be used in the `serverMetadata()` function, like in the UI, switched from using the `/api/ga4gh/v2/metadata` call to `/ga4gh/trs/v2/service-info`.
Output from `--server-metadata` before:
```
{
"apiVersion": "2.0.0",
"country": "CAN",
"friendlyName": "Dockstore",
"version": "1.13.1"
}
Dockstore server: https://dockstore.org/api
```
Output from `--server-metadata` after:
```
{
"contactUrl": "https://discuss.dockstore.org/t/opening-helpdesk-tickets/1506",
"createdAt": "Jul 1, 2020, 8:00:00 PM",
"description": "Dockstore is an implementation of the GA4GH Tool Registry API which is a standard for listing and describing …
```
> CLI Using Beta TRS API - SEAB-5206

- checkstyle.xml
- dockstore-cli-integration-testing/src/test/java/io/dockstore/client/cli/ClientIT.java
- dockstore-cli-integration-testing/src/test/java/io/dockstore/client/cli/CromwellIT.java
- dockstore-cli-integration-testing/src/test/resources/hosted_metadata/Dockstore.cwl
- dockstore-cli-integration-testing/src/test/resources/hosted_metadata/sorttool.cwl
- dockstore-client/README.md
- dockstore-client/pom.xml
- dockstore-client/src/main/java/io/dockstore/client/cli/JCommanderUtility.java
- dockstore-client/src/main/java/io/dockstore/client/cli/PluginClient.java
- dockstore-client/src/main/java/io/dockstore/client/cli/YamlVerifyUtility.java
- dockstore-client/src/main/java/io/dockstore/client/cli/nested/AbstractEntryClient.java
- dockstore-client/src/main/java/io/dockstore/client/cli/nested/BaseLanguageClient.java
- dockstore-client/src/main/java/io/dockstore/client/cli/nested/DepCommand.java
- dockstore-client/src/main/java/io/dockstore/client/cli/nested/ToolClient.java
- dockstore-client/src/main/java/io/dockstore/client/cli/nested/WorkflowClient.java
- dockstore-client/src/main/java/io/github/collaboratory/cwl/CWLClient.java
- dockstore-client/src/test/resources/topmed_freeze3_calling.wdl
- dockstore-file-plugin-parent/README.md
- dockstore-file-plugin-parent/src/main/java/io/dockstore/provision/ProgressPrinter.java
- openapi-java-wes-client/src/main/resources/OPENAPI_CREATION.md
- pom.xml
This PR corrects a few typos in the CLI.
Whilst going in to fix the typo that @coverbeck  spotted in the CLI, I noticed a few others. 
To find all of the typos in this PR I used cspell. Specifically this command (more info [here](https://cspell.org/docs/getting-started/))
```
cspell --words-only --unique "**" | sort --ignore-case >> project-words.txt
```
which was helpful, as it gave me a list of all the words that it had found to be misspelled in the CLI, and then I just wen through and searched for the ones that were actually misspelled and corrected them. This process took about 15 minutes, so if you like I could do this to https://github.com/dockstore/dockstore and https://github.com/dockstore/dockstore-ui2 fairly quickly.
- Ensure that all of …
> Corrected Typos found in CLI

- dockstore-cli-integration-testing/src/test/java/io/dockstore/client/cli/ClientIT.java
- dockstore-client/src/main/java/io/dockstore/client/cli/CheckerClient.java
- dockstore-client/src/main/java/io/dockstore/client/cli/PluginClient.java
- dockstore-client/src/main/java/io/dockstore/client/cli/nested/AbstractEntryClient.java
- dockstore-client/src/main/java/io/dockstore/client/cli/nested/Verify.java
- dockstore-client/src/main/java/io/dockstore/client/cli/nested/WorkflowClient.java
This PR does two things,
**1:**
It modifies this testing method,
https://github.com/dockstore/dockstore-cli/blob/411f34dcbee710e796d830b2be3c122e54830fbf/dockstore-cli-integration-testing/src/test/java/io/dockstore/client/cli/ClientIT.java#L449
such that it now checks that all of the arguments given in `argv` are on the help page.
**2:**
It fixes the following help pages (trying out the toggle feature here, if they are causing issues let me know and I can post the before and after help pages in the comments),
<details>
<summary><b>dockstore plugin download --help</b></summary>
**Before:**
```
fhembroff@LL6496-Fhembr:~/Documents/work/incorrect-help-pages/dockstore-cli$ dockstore plugin download --help --script
____             _        _                 
|  _ \  ___   ___| …
```
> Fix Incorrect Help Page and made tests around help pages more robust

- dockstore-cli-integration-testing/src/test/java/io/dockstore/client/cli/BasicIT.java
- dockstore-cli-integration-testing/src/test/java/io/dockstore/client/cli/ClientIT.java
- dockstore-cli-integration-testing/src/test/java/io/dockstore/client/cli/GeneralIT.java
- dockstore-cli-integration-testing/src/test/java/io/dockstore/client/cli/GeneralWorkflowIT.java
- dockstore-cli-integration-testing/src/test/java/io/dockstore/client/cli/GitHubAppToolIT.java
- dockstore-cli-integration-testing/src/test/java/io/dockstore/client/cli/LaunchWorkflowIT.java
- dockstore-cli-integration-testing/src/test/java/io/dockstore/client/cli/ManualPublishWorkflowIT.java
- dockstore-cli-integration-testing/src/test/java/io/dockstore/client/cli/SingularityIT.java
- dockstore-cli-integration-testing/src/test/java/io/dockstore/client/cli/StarIT.java
- dockstore-cli-integration-testing/src/test/java/io/dockstore/client/cli/WDLWorkflowIT.java
- dockstore-cli-integration-testing/src/test/java/io/dockstore/client/cli/WorkflowIT.java
- dockstore-client/src/main/java/io/dockstore/client/cli/CheckerClient.java
- dockstore-client/src/main/java/io/dockstore/client/cli/nested/AbstractEntryClient.java
- dockstore-client/src/main/java/io/dockstore/client/cli/nested/CromwellLauncher.java
- dockstore-client/src/main/java/io/dockstore/client/cli/nested/WesLauncher.java
- dockstore-client/src/main/java/io/dockstore/client/cli/nested/WorkflowClient.java
Whilst doing this [PR](https://github.com/dockstore/dockstore-cli/pull/231) I noticed that the strings `"WDL"` and `"CWL"` show up a lot in the CLI. So, this PR moves `"WDL"` and `"CWL"` to constants.
The constants that I am using (which I got from `io.dockstore.common.DescriptorLanguage`), have `WDL` and `CWL` capitalized. This not an issue, as our code permits any case to be used when dealing with the commands `CWL` and `WDL`. Also, if this was an issue, I imagine it would be picked up by our tests.
Ensure that all tests run correctly.
**Issue**
I stated that I would do this in this [comment](https://github.com/dockstore/dockstore-cli/pull/231#discussion_r1134237050).
**Security**
If there are any concerns that require extra attention from the …
> Moved CWL and WDL to constants

- .circleci/config.yml
- dockstore-client/src/main/java/io/github/collaboratory/cwl/CWLClient.java
Currently, generating test parameter JSON files for CWL workflows with arrays for `items` ([example](https://qa.dockstore.org/workflows/github.com/bcbio/bcbio_validation_workflows/wes-agha-test-gcp:master?tab=files)) results in a `ClassCastException` error due to these [lines](https://github.com/dockstore/cwlavro/blob/83e0bd298060472bea42d638460c5899a67380d0/cwlavro-tools/src/main/java/io/cwl/avro/CWL.java#L307-L308).
This PR adds an error handling message to let users know that it's file structure is not supported yet. 
Before fix: 
```
dockstore workflow convert entry2json --entry github.com/bcbio/bcbio_validation_workflows/wes-agha-test-gcp:master
Current version : 1.13.1
You have the most recent stable release.
If you wish to upgrade to the latest unstable version, …
```
> DOCK-2349: added error handling message for CWL JSON conversion

- dockstore-client/src/test/java/io/dockstore/client/cli/LaunchTestIT.java
- dockstore-client/src/test/resources/arguments.cwl
All dockstore-cli builds past a certain date are failing, regardless of branch which is weird. 
Turns out, a docker image expired
Non confidential builds should pass again after this ticket
**Issue**
https://ucsc-cgl.atlassian.net/browse/SEAB-5558
**Security**
> replace expired docker image

- .circleci/config.yml
- .gitignore
- dockstore-cli-reports/pom.xml
- pom.xml
Follow-up from https://github.com/dockstore/dockstore-support/pull/469
Noticed https://artifacts.oicr.on.ca/artifactory/collab-release/io/dockstore/reports/ had a mix of stuff from different projects (presumably missed since they aren't actually used for anything and the machine user doesn't have overwrite permissions)
No change  to coverage information
**Issue**
n/a
**Security**
> rename reports to avoid clash

- dockstore-client/src/main/java/io/dockstore/client/cli/nested/AbstractEntryClient.java
- dockstore-client/src/main/java/io/dockstore/client/cli/nested/BaseLanguageClient.java
- dockstore-client/src/main/java/io/github/collaboratory/cwl/CWLClient.java
This PR removes the `isWesCommand()` invocations because the code is never executed. Charles' assessment in the issue is correct:
> if launching a workflow via WES, the CLI creates a WESLauncher, which doesn't instantiate a BaseLanguageClient subclass instance -- so the code never even executes for a WES launch.
Looking at the git blames, it appears that this code used to be executed when the language clients would do the WES launch: https://github.com/dockstore/dockstore/pull/2156. However, we eventually moved away from this model and abstracted the WES launch to be independent of the language clients because it doesn't need it https://github.com/dockstore/dockstore-cli/pull/100. The unexecuted WES checks are just code that never got removed when we abstracted the WES …
> Remove wes checks that are never executed

- dockstore-cli-integration-testing/generated/src/main/resources/pom.xml
- dockstore-cli-integration-testing/src/test/java/io/dockstore/client/cli/YamlClientIT.java
- dockstore-cli-reports/generated/src/main/resources/pom.xml
- dockstore-client/generated/src/main/resources/pom.xml
- dockstore-file-plugin-parent/generated/src/main/resources/pom.xml
- openapi-java-wes-client/generated/src/main/resources/pom.xml
- pom.xml
- support/generated/src/main/resources/pom.xml
Has been tripping up the nightly compatibility (with the webservice) builds. 
Broad artifactory has moved and gives out corrupted info with a redirect if we point at the wrong URL
Nightly cron build should work
https://github.com/dockstore/dockstore-cli/actions/workflows/cron.yml
**Issue**
n/a
**Security**
> new broad artifactory location

- dockstore-client/src/main/java/io/dockstore/common/FileProvisioning.java
This PR allows file provisioning to display source and destination paths.
1. Remove ~/.dockstore/libraries/
2. Run dockstore workflow launch --entry github.com/dockstore-testing/Metaphlan-WDL:master and see cromwell download with the source and destination path logged like below.
```
> dockstore workflow launch --entry github.com/dockstore-testing/Metaphlan-WDL:master 
WARNING: Docker is not running. If this workflow uses Docker, it will fail.
Saving https://github.com/broadinstitute/cromwell/releases/download/84/cromwell-84.jar to /home/nhyun/.dockstore/libraries/cromwell-84.jar
[##########################                        ] 53%
```
**Issue**
https://ucsc-cgl.atlassian.net/browse/DOCK-2323
**Security**
If there are any concerns that require …
> DOCK-2323: Log source and destination paths for file provisioning

- .circleci/config.yml
- dockstore-cli-integration-testing/pom.xml
- dockstore-cli-integration-testing/src/test/java/io/dockstore/client/cli/WDLWorkflowIT.java
- dockstore-cli-integration-testing/src/test/java/io/dockstore/client/cli/WorkflowIT.java
Re-enable failing CLI test by turning off Java assertions in the org.hibernate and subpackages. It also enabled the removal of System.exit catch that is no longer necessary.
This is less than ideal, but note that in prod the web service is not running with assertions enabled.
Notes:
* The Surefire plugin by default turns on Java assertions
* I was initially unable to reproduce the bug with a local "regular" web service running, because I don't run the web service with assertions enabled. But If I set a breakpoint in the Java code, in org.hibernate.collection.spi.PersistentMap#injectLoadedState, on the `assert this.isInitializing()`, I can see the assertion would fail if assertions were enabled.
* Semi-digression, I can't even start the web service locally with assertions …
> Re-enable failing CLI Test

- .circleci/config.yml
This PR restores the Slack notification for nightly CLI build failures, which was removed after moving the nightly cron to CircleCI (https://github.com/dockstore/dockstore-cli/pull/268). Notifications are set up appear in #dockstore-dev-alerts.
In config.yml, verify that the Slack notification is configured as expected. See https://oicr.slack.com/archives/C0151UDNR9R/p1711479933594839 for a successful test run of the `slack/notify` setup (without the nightly condition).
Since the CLI nightly workflow consists of multiple jobs, the PR currently proposes separate Slack notifications for the build, unit tests, and integration tests. Are there any jobs that should be added/removed?
Note: I originally created a new Slack app called "Dockstore CLI Build", …
> SEAB-6097: Nightly CLI build failure should notify in Slack

- keysmap.list
A recent web service PR, dockstore/dockstore#/5923, updated the Kohsuke GitHub library, which has a bad signature. This caused the CLI builds against the web service develop branch to fail.
Note that the web service PR also needed to add the `badSig` to keymap.list.
The nightly [builds](https://app.circleci.com/pipelines/github/dockstore/dockstore-cli?branch=develop) here should pass.
**Issue**
SEAB-6567
**Security**
> Fix nightly build failure against develop

- THIRD-PARTY-LICENSES.txt
- dockstore-cli-integration-testing/generated/src/main/resources/pom.xml
- dockstore-cli-reports/generated/src/main/resources/pom.xml
- dockstore-client/generated/src/main/resources/pom.xml
- pom.xml
- scripts/install-tests.sh
This PR fixes the CLI build, which started failing when I merged the hotfix tag to develop, by updating the webservice tag. I created a new webservice tag after the hotfix release tag was merged to develop.
Builds should pass
**Issue**
n/a
**Security**
> Update webservice tag after hotfix merge

- dockstore-cli-integration-testing/generated/src/main/resources/pom.xml
- dockstore-cli-integration-testing/pom.xml
- dockstore-cli-reports/generated/src/main/resources/pom.xml
- dockstore-client/generated/src/main/resources/pom.xml
- dockstore-file-plugin-parent/generated/src/main/resources/pom.xml
- openapi-java-wes-client/generated/src/main/resources/pom.xml
- pom.xml
- support/generated/src/main/resources/pom.xml
Noticed CLI nightly builds have been failing since August 10th, investigating. 
Added Java 21 compatibility (this is different from https://github.com/dockstore/dockstore-cli/pull/293 in that this branch only allows us to work with Java 21 locally whereas that branch does the actual testing on Java 21 in a newer machine image)
Also iterated the minor version. Noticed that some nightly regression tests were failing, expecting older versions of cwltool. 
Think that our client was testing itself as a 15.0-SNAPSHOT and thus getting the wrong requirements file after https://github.com/dockstore/dockstore/pull/5958
Wait a day and see if nightly build passes
**Issue**
n/a
**Security**
If there are any concerns that require extra attention from the security …
> java 21 compatibility and minor version iteration

- .circleci/config.yml
- pom.xml
Build failure for CLI nightly build traced initially to bad semantic versioning for uploaded artifacts from latter linked ticket. 
To better address the spirit of the nightly build, instructed Maven to only update to snapshot versions that do not seem to come from feature branches and release branches (which will have an extra hyphen as described in linked ticket)
See if nightly builds succeed after merge
**Issue**
While working on https://ucsc-cgl.atlassian.net/browse/SEAB-6808 had interaction with
https://github.com/dockstore/dockstore/pull/6043 or more accurately https://github.com/dockstore/workflow-actions/pull/3
**Security**
None
> allow nightly builds to ignore artifact uploads from feature branches
