- checkstyle-suppressions.xml
- dockstore-cli-integration-testing/src/test/java/io/dockstore/common/package-info.java
- dockstore-cli-integration-testing/src/test/java/io/dockstore/models/package-info.java
- dockstore-client/pom.xml
- dockstore-client/src/test/java/io/dockstore/client/cli/ClientTestIT.java
- dockstore-client/src/test/java/io/dockstore/client/cli/LaunchNoInternetTestIT.java
- dockstore-client/src/test/java/io/dockstore/client/cli/LaunchTestIT.java
- dockstore-client/src/test/java/io/dockstore/client/cli/NextflowIT.java
- dockstore-client/src/test/java/io/dockstore/client/cli/UpgradeTestIT.java
- dockstore-client/src/test/java/io/dockstore/client/cli/WorkflowInDirectoryTestIT.java
- dockstore-client/src/test/java/io/dockstore/client/cli/nested/ToolClientTest.java
- dockstore-client/src/test/java/io/dockstore/client/cli/nested/package-info.java
- dockstore-client/src/test/java/io/dockstore/client/cli/package-info.java
- dockstore-client/src/test/java/io/dockstore/common/FileProvisionTest.java
- dockstore-client/src/test/java/io/dockstore/common/package-info.java
- dockstore-client/src/test/java/io/github/collaboratory/cwl/LauncherIT.java
- dockstore-client/src/test/java/io/github/collaboratory/cwl/SecondaryFilesUtilityIT.java
- dockstore-client/src/test/java/io/github/collaboratory/cwl/package-info.java
- dockstore-client/src/test/java/io/github/collaboratory/package-info.java
- dockstore-client/src/test/java/io/github/collaboratory/wdl/WDLClientTest.java
- dockstore-client/src/test/java/io/github/collaboratory/wdl/package-info.java
also see https://github.com/dockstore/dockstore/pull/2920 and
https://github.com/dockstore/dockstore/pull/2924
> follow up with dockstore checkstyle expansion

- pom.xml
Test with updated core that has tagged openapi endpoints
See also https://github.com/dockstore/dockstore/pull/3117
> Update openapi tags

- dockstore-client/bin/dockstore
Working on https://github.com/dockstore/dockstore/issues/3130
> Fix download location due to refactoring

- dockstore-client/src/main/java/io/dockstore/client/cli/nested/ToolClient.java
- dockstore-client/src/main/java/io/dockstore/client/cli/nested/WorkflowClient.java
For dockstore/dockstore#2395
Doesn't seem to be organization unstarring in the CLI as far as i can tell
> Use the new restful starring endpoints

- dockstore-client/src/main/java/io/dockstore/client/cli/nested/AbstractEntryClient.java
- dockstore-client/src/main/java/io/dockstore/client/cli/nested/WESLauncher.java
- openapi-java-wes-client/src/main/resources/OPENAPI_CREATION.md
- openapi-java-wes-client/src/main/resources/workflow-execution_service-1.0.0-oas3-openapi.yaml
Addresses:
Evaluate Illumina WES endpoint with Dockstore CLI
https://ucsc-cgl.atlassian.net/browse/SEAB-862
Disable WES workflow launch for local entry
https://ucsc-cgl.atlassian.net/browse/SEAB-1082
> Changes to support Illumina WES endpoints

- dockstore-client/src/main/java/io/dockstore/client/cli/nested/AbstractEntryClient.java
- dockstore-client/src/main/java/io/dockstore/client/cli/nested/WESLauncher.java
Addresses https://ucsc-cgl.atlassian.net/browse/DOCK-1330
> Improve help for WES launch command

- dockstore-client/src/main/java/io/dockstore/client/cli/nested/ApiClientExtended.java
Changes to support DNAStack WES endpoints
I.e. set correct content types
> Support DNAStack WES endpoints

- dockstore-client/src/main/java/io/dockstore/client/cli/Client.java
Addresses https://ucsc-cgl.atlassian.net/browse/DOCK-1334
> Obtain Dockstore command line script and jar from dockstore-cli repo

- dockstore-cli-integration-testing/src/test/java/io/dockstore/client/cli/CromwellIT.java
- dockstore-cli-integration-testing/src/test/resources/pass_escape_in_input.wdl
- dockstore-cli-integration-testing/src/test/resources/pass_escape_in_input.wdl.json
- dockstore-client/src/main/java/io/dockstore/common/WDLFileProvisioning.java
Addresses:
dockstore/dockstore#3562
https://ucsc-cgl.atlassian.net/browse/DOCK-1416
> don't replace backslashes

- dockstore-client/src/main/java/io/dockstore/client/cli/ArgumentUtility.java
- dockstore-client/src/main/java/io/dockstore/client/cli/nested/WorkflowClient.java
Main issue: https://github.com/dockstore/dockstore/issues/3609
Before:
```
$ dockstore workflow refresh --entry github.com/GFJHogue/one-workflow-many-ways/bamqc_NFL
Refreshing workflow...
13:32:28.549 [main] ERROR io.dockstore.client.cli.ArgumentUtility - io.swagger.client.ApiException: Cannot refresh .dockstore.yml workflows
at io.swagger.client.ApiClient.invokeAPI(ApiClient.java:718)
at io.swagger.client.api.WorkflowsApi.refreshWithHttpInfo(WorkflowsApi.java:1823)
at io.swagger.client.api.WorkflowsApi.refresh(WorkflowsApi.java:1780)
at io.dockstore.client.cli.nested.WorkflowClient.refreshTargetEntry(WorkflowClient.java:631)
at io.dockstore.client.cli.nested.AbstractEntryClient.refresh(AbstractEntryClient.java:492)
at io.dockstore.client.cli.nested.AbstractEntryClient.processEntryCommands …
```
> workflow refresh no stack trace for failing .dockstore.yml workflows

- dockstore-cli-integration-testing/src/test/java/io/dockstore/client/cli/StarIT.java
- dockstore-client/src/main/java/io/dockstore/client/cli/SwaggerUtility.java
- dockstore-client/src/main/java/io/dockstore/client/cli/nested/AbstractEntryClient.java
- dockstore-client/src/main/java/io/dockstore/client/cli/nested/ToolClient.java
- dockstore-client/src/main/java/io/dockstore/client/cli/nested/WorkflowClient.java
* Fix for starring
Same PR to hotfix branch in case we make a hotfix
> Feature/star fix (#18) (#36)

- dockstore-cli-integration-testing/src/test/java/io/dockstore/client/cli/BasicIT.java
- dockstore-cli-integration-testing/src/test/java/io/dockstore/client/cli/GeneralWorkflowIT.java
Follow-up https://github.com/dockstore/dockstore/issues/3569#issuecomment-721203306
> Follow #3569

- dockstore-cli-integration-testing/pom.xml
- dockstore-client/pom.xml
- dockstore-file-plugin-parent/pom.xml
- openapi-java-wes-client/pom.xml
- pom.xml
- reports/pom.xml
- support/pom.xml
Merging release branch into develop according to instructions in step four of https://wiki.oicr.on.ca/display/DOC/Dockstore+Releases
> Merge 1.10.0 alpha.0 release into develop

- dockstore-client/src/main/java/io/dockstore/client/cli/nested/CromwellLauncher.java
Use latest version of Cromwell in CLI
> bump cromwell version

- dockstore-client/src/main/java/io/dockstore/client/cli/Client.java
Addresses https://ucsc-cgl.atlassian.net/browse/SEAB-3147
> set proper dockstore version for script

- .github/workflows/cron.yml
Action seems remarkably inflexible, trying to follow an example even more closely
> change to payload method

- dockstore-client/pom.xml
- dockstore-client/src/main/java/io/dockstore/client/cli/Client.java
- dockstore-client/src/main/java/io/dockstore/client/cli/nested/AbstractEntryClient.java
- dockstore-client/src/main/java/io/dockstore/client/cli/nested/WESLauncher.java
- dockstore-client/src/main/java/io/github/collaboratory/cwl/CWLClient.java
- dockstore-client/src/test/java/io/dockstore/client/cli/LaunchTestIT.java
- dockstore-client/src/test/resources/malicious.input.yaml
- pom.xml
Equivalent to merging hotfix/1.11.1 into develop
> Hotfix 1.11.1 merged to develop

- dockstore-cli-integration-testing/src/test/java/io/dockstore/client/cli/BaseIT.java
- dockstore-cli-integration-testing/src/test/java/io/dockstore/client/cli/GeneralWorkflowIT.java
- dockstore-cli-integration-testing/src/test/java/io/dockstore/client/cli/GitHubAppToolIT.java
- dockstore-client/src/main/java/io/dockstore/client/cli/nested/WebserviceWorkflowClient.java
- dockstore-client/src/main/java/io/dockstore/client/cli/nested/WorkflowClient.java
- dockstore-client/src/main/java/io/github/collaboratory/cwl/CWLClient.java
For SEAB-3732
Upon discussion, GitHub App Tool will be launched with `./dockstore workflow` .
Some webservice endpoints will need to be added for search as well as optimizations (will need to create issues for them).
> Feature/seab 3732/app tools

- README.md
Updates a broken icgc.org link in the readme.
---------
> Update broken icgc.org link in readme

- README.md
Mostly just to trigger lgtm, also fixes typo
> trigger lgtm

- README.md
> Remove stale configuration instructions

- .github/PULL_REQUEST_TEMPLATE.md
>  Update PR template for docs

- dockstore-client/generated/src/main/resources/pom.xml
- dockstore-client/pom.xml
This PR restricts the Postgres dependency in the CLI to only the test dependencies.
Verify the scope for the Postgres dependency is set to test.
**Issue**
https://ucsc-cgl.atlassian.net/browse/SEAB-4927
> SEAB-4927 Restricted postgres dependency to only test

- dockstore-client/src/main/java/io/dockstore/client/cli/nested/WorkflowClient.java
This PR corrects a small bug in the CLI. It makes it so that if the `--zip` flag is not specified, the zip file will not be left on the computer, it will be deleted.
This is in line with the documentation of the command line.
```
fhembroff@LL6496-Fhembr:~/Documents/work/dockstore-cli/dockstore-client/target$ java -jar dockstore-client-1.14.0-SNAPSHOT-shaded.jar workflow download
____             _        _                 
|  _ \  ___   ___| | _____| |_ ___  _ __ ___ 
| | | |/ _ \ / __| |/ / __| __/ _ \| '__/ _ \
| |_| | (_) | (__|   <\__ \ || (_) | | |  __/
|____/ \___/ \___|_|\_\___/\__\___/|_|  \___|
---------------------------------------------
See https://www.dockstore.org for more information
Usage: dockstore workflow download --help
dockstore workflow download …
```
> Deleted the zip file once it is unzipped.

- .circleci/config.yml
Update is already done behind the scenes on circle ci. Either both are installed or there's an alias anyway
Builds continue to function
**Issue**
https://github.com/dockstore/dockstore/issues/5415
**Security**
> update docker compose

- .github/snapshot-mvn-settings.xml
- .github/workflows/deploy_snapshot.yml
Adding auto-deployment of nightly snapshots, for possible use in development CLI
Look in artifacts.oicr.on.ca, the collab-snapshot repo should have cli snapshots along with webservice snapshots
**Issue**
A building block for https://ucsc-cgl.atlassian.net/browse/SEAB-5278
**Security**
> add auto deploy for testing

- dockstore-cli-integration-testing/generated/src/main/resources/pom.xml
- dockstore-cli-reports/generated/src/main/resources/pom.xml
- dockstore-client/generated/src/main/resources/pom.xml
- pom.xml
Pairs with https://github.com/dockstore/dockstore/pull/5678
Updates bom but removes hierarchy change
Should pass builds
**Issue**
https://github.com/dockstore/dockstore/pull/5678
https://github.com/dockstore/dockstore/issues/5605
**Security**
> update dockstore version

- dockstore-cli-integration-testing/generated/src/main/resources/pom.xml
- dockstore-cli-reports/generated/src/main/resources/pom.xml
- dockstore-client/generated/src/main/resources/pom.xml
- pom.xml
Update to latest alpha version (looks like reverting the hierarchy change makes this a no-op)
n/a except for passing builds on this PR
**Issue**
Part of https://ucsc-cgl.atlassian.net/browse/SEAB-5921
**Security**
> update to latest 1.15 alpha

- THIRD-PARTY-LICENSES.properties
Fix  failing cron builds ( https://github.com/dockstore/dockstore-cli/actions/workflows/cron.yml ) due to cromwell update in webservice develop https://github.com/dockstore/dockstore/pull/5741
Note, this is an example of a case where the cron builds are working to  *some* extent 
https://ucsc-cgl.atlassian.net/browse/SEAB-5853 @coverbeck 
After merge, the cron builds (first  link)  should be working again
**Issue**
n/a 
Noted while doing email triage
**Security**
> need this for failing cron with current develop

- dockstore-cli-integration-testing/generated/src/main/resources/pom.xml
- dockstore-cli-reports/generated/src/main/resources/pom.xml
- dockstore-client/generated/src/main/resources/pom.xml
- pom.xml
Update and test cli with newer webservice components
Build should succeed
**Issue**
https://ucsc-cgl.atlassian.net/browse/SEAB-6093
**Security**
> test core update

- .github/workflows/mvnw.yml
See https://github.com/dockstore/dockstore/pull/5802.
Take a look at what the new queries are scanning for, and evaluate whether they add value to the build/scan process. This is a link to the [CodeQL issues raised by the `security-and-quality` scan](https://github.com/dockstore/dockstore-cli/security/code-scanning?query=is%3Aopen+branch%3Adock-2465%2Fcodeql-queries+sort%3Acreated-desc).
The outputs under "Perform CodeQL analysis" in the workflow logs might store information about the scans:
- [Link to workflow log using `security-and-quality` scan](https://github.com/dockstore/dockstore-cli/actions/runs/7758375026/job/21160003235)
- [Link to workflow log using default CodeQL scan](https://github.com/dockstore/dockstore-cli/actions/runs/7759031815/jo …
> DOCK-2465: Try running extended CodeQL query suite (CLI)

- keysmap.list
Getting ahead of https://github.com/dockstore/dockstore/pull/6070
This recently broke due to a dropwizard update a month or so ago in a similar way
Nighly build should be ok at least from a GPG map perspective after linked PR is merged
**Issue**
https://ucsc-cgl.atlassian.net/browse/SEAB-6876
**Security**
> prep for dropwizard update in develop
